 CREATE USER DEMO IDENTIFIED BY DEMO_PASSWORD;
 GRANT
      CREATE SESSION, 
	  ALTER SESSION, 
	  UNLIMITED TABLESPACE, 
	  CREATE TABLESPACE,
	  CREATE SEQUENCE,
	  CREATE TABLE, 
	  CREATE VIEW, 
	  CREATE PROCEDURE, 
	  CREATE TRIGGER, 
	  CREATE SYNONYM 
 TO DEMO;